name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Zig build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v2

      - name: Build and test
        run: zig build test
